name: FORE1GN BODY
favicon: null
layout_spectrum: 0.68419
typography_spectrum: 0.25804
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#070707'
    - '#f5f5f5'
    - '#9a9a9a'
    - '#434343'
    - '#727272'
  brandStrength: 0
  lightness: 0.25
  saturation: 0.16343028517439961
  rhythmicContrast: 0.5495459523517638
purpose: []
