name: FORE1GN BODY
favicon: null
layout_spectrum: 0.5392315429635346
typography_spectrum: 0.18643429968506098
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2b241e'
    - '#943532'
    - '#c84041'
    - '#8f692c'
    - '#a78334'
  brandStrength: 0.8443327944260091
  lightness: 0.9045623536221683
  saturation: 0.16343028517439961
  rhythmicContrast: 0.5495459523517638
purpose: []
